cover:
  - platform: template
    covers:
      zaluzie:
        friendly_name: "Covers"
        device_class: blind
        value_template: "{{states('cover.zaluzie_leva')}}"
        icon_template: >-
          {% if is_state('cover.left_cover', 'open') %}mdi-blinds-open{% else %}mdi:blinds{% endif %}
        tilt_template: "{{state_attr('cover.left_cover', 'current_tilt_position')}}"
        open_cover:
          service: script.cover_group
          data:
            modus: "open"
        close_cover:
          service: script.cover_group
          data:
              modus: "close"
        stop_cover:
          service: script.cover_group
          data:
            modus: "stop"
        set_cover_tilt_position:
          service: script.cover_group_position
          data:
            tilt_position: "{{tilt}}"