esphome:
  name: Xmas_tree
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Your SSID"
  password: "Your password"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.0.202
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stromek Fallback Hotspot"
    password: "rVvLFoBIKVDp"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: binary
    name: "Stromek"
    output: output_gpio

output:
  - platform: gpio
    id: output_gpio
    pin: 2